"""
run_all.py — Config-driven runner for the ABM factorial simulation.

Usage:
    python run_all.py --config configs/main_calibrated.yaml

Implements the full model described in the CCR manuscript:
  - 4 network topologies: BA, ER, WS, SBM
  - N message conditions with configurable delta_m per condition
  - 3 inoculation strategies: none, random, hub
  - 3 seeding regimes: single_shot, burst, continuous (+ dose-matched variant)
  - Opinion update: Eqs. 1–3 from the paper
  - Primary outcomes: mean total shift (Eq. 4), mean signed shift (Eq. 5), conversion rate (Eq. 6)
  - Outputs: raw CSV per run + seed manifest
"""

import argparse
import csv
import hashlib
import json
import os
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import networkx as nx
import yaml


# ── Stable hashing ────────────────────────────────────────────────────────────

def stable_hash_int(s: str, modulo: int = 10000) -> int:
    """Deterministic, process-independent hash (Python's built-in hash() is salted)."""
    h = hashlib.sha256(s.encode("utf-8")).hexdigest()
    return int(h[:12], 16) % modulo


# ── CLI ───────────────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--config", required=True, help="Path to YAML config file")
    p.add_argument("--seed_manifest", default=None,
                   help="Optional path to a seed_manifest.csv. If given, seeds are replayed "
                        "from the manifest (exact reproduction of bundled outputs) instead of "
                        "being generated by the stable SHA-256 seed generator.")
    return p.parse_args()


def load_seed_manifest(path: str) -> dict:
    """Load a seed manifest into a lookup keyed by cell identity.

    Key: (topology, message_condition, inoculation, seeding_regime, replication)
    Value: dict of seed_net/seed_attr/seed_sim/seed_inoc.
    Accepts both the unified field names and the legacy names (condition/regime/rep).
    """
    lookup = {}
    with open(path, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            cond = r.get("message_condition", r.get("condition"))
            regime = r.get("seeding_regime", r.get("regime"))
            rep = int(r.get("replication", r.get("rep")))
            key = (r["topology"], cond, r["inoculation"], regime, rep)
            seed_sim = r.get("seed_sim")
            lookup[key] = {
                "master_seed": int(r["master_seed"]) if r.get("master_seed") else None,
                "seed_net": int(r.get("seed_net") or r["network_seed"]),
                "seed_attr": int(r.get("seed_attr") or r["initialization_seed"]),
                "seed_seeding": int(r.get("seed_seeding", r.get("seeding_seed", seed_sim))),
                "seed_sharing": int(r.get("seed_sharing", r.get("sharing_seed", seed_sim))),
                "seed_noise": int(r.get("seed_noise", r.get("noise_seed", seed_sim))),
                "seed_sim": int(seed_sim) if seed_sim else None,
                "seed_inoc": int(r.get("seed_inoc") or r["inoculation_seed"]),
            }
    return lookup


# ── Config loading ────────────────────────────────────────────────────────────

def load_config(path: str) -> dict:
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


# ── Network construction ──────────────────────────────────────────────────────

def build_network(topology: str, n: int, opinion_clusters: np.ndarray, seed: int) -> nx.Graph:
    """Return a connected undirected graph for the given topology label.

    SBM block membership is aligned with initial opinion clusters so that
    intra-cluster edges are more probable than inter-cluster edges.
    """
    if topology == "BA":
        g = nx.barabasi_albert_graph(n, m=3, seed=seed)

    elif topology == "ER":
        p = 6.0 / (n - 1)
        g = nx.erdos_renyi_graph(n, p=p, seed=seed)
        # Ensure full connectivity by bridging isolated components
        if not nx.is_connected(g):
            rng = np.random.default_rng(seed + 99)
            comps = sorted(nx.connected_components(g), key=len, reverse=True)
            for comp in comps[1:]:
                u = rng.choice(list(comps[0]))
                v = rng.choice(list(comp))
                g.add_edge(int(u), int(v))

    elif topology == "WS":
        g = nx.watts_strogatz_graph(n, k=6, p=0.10, seed=seed)

    elif topology == "SBM":
        # Two blocks aligned with opinion clusters (opposition vs support+centrist)
        # Assign nodes to blocks by initial opinion sign
        block0 = [i for i, o in enumerate(opinion_clusters) if o < 0]   # opposition
        block1 = [i for i, o in enumerate(opinion_clusters) if o >= 0]  # support + centrist
        sizes = [len(block0), len(block1)]
        # p_intra ≈ 5× p_inter; calibrate so mean degree ≈ 6
        # E[degree_i] ≈ p_intra*(size_i-1) + p_inter*size_j ≈ 6
        n0, n1 = sizes
        # Solve: 5p*(n0-1) + p*n1 = 6  (for block0 nodes)
        p_inter = 6.0 / (5.0 * (n0 - 1) + n1)
        p_intra = 5.0 * p_inter
        p_matrix = [[p_intra, p_inter], [p_inter, p_intra]]
        g = nx.stochastic_block_model(sizes, p_matrix, seed=seed)
        # Relabel so nodes match original agent indices (block0 first, then block1)
        mapping = {}
        for new_idx, old_idx in enumerate(block0 + block1):
            mapping[new_idx] = old_idx
        g = nx.relabel_nodes(g, mapping)
    else:
        raise ValueError(f"Unknown topology: {topology!r}. Choose BA, ER, WS, SBM.")

    return g


# ── Agent initialisation ──────────────────────────────────────────────────────

@dataclass
class AgentState:
    opinions: np.ndarray             # [-1, 1]
    susceptibility: np.ndarray       # [0, 1], Beta(2,5)
    disclosure_sensitivity: np.ndarray  # [0, 1], Uniform
    inoculated: np.ndarray           # bool
    cumulative_exposure: np.ndarray  # int
    direct_exposure: np.ndarray      # int
    secondhand_exposure: np.ndarray  # int


def init_agents(n: int, seed: int) -> AgentState:
    rng = np.random.default_rng(seed)
    n_opp = int(0.45 * n)
    n_sup = int(0.45 * n)
    n_cen = n - n_opp - n_sup

    opinions = np.concatenate([
        np.clip(rng.normal(-0.5, 0.20, n_opp), -1.0, 0.0),
        np.clip(rng.normal( 0.5, 0.20, n_sup),  0.0, 1.0),
        np.clip(rng.normal( 0.0, 0.10, n_cen), -0.2, 0.2),
    ])
    rng.shuffle(opinions)

    return AgentState(
        opinions=opinions,
        susceptibility=rng.beta(2, 5, n),
        disclosure_sensitivity=rng.uniform(0, 1, n),
        inoculated=np.zeros(n, dtype=bool),
        cumulative_exposure=np.zeros(n, dtype=int),
        direct_exposure=np.zeros(n, dtype=int),
        secondhand_exposure=np.zeros(n, dtype=int),
    )


# ── Inoculation ───────────────────────────────────────────────────────────────

def apply_inoculation(
    g: nx.Graph,
    agents: AgentState,
    strategy: str,
    budget_fraction: float,
    kappa: float,
    compliance_fraction: float,
    seed: int,
) -> None:
    rng = np.random.default_rng(seed)
    n = len(agents.opinions)
    k = max(1, int(budget_fraction * n))

    if strategy == "none":
        return
    elif strategy == "random":
        idx = rng.choice(n, size=k, replace=False)
    elif strategy == "hub":
        degree_seq = np.array([d for _, d in g.degree()])
        idx = np.argsort(degree_seq)[-k:]
    else:
        raise ValueError(f"Unknown inoculation strategy: {strategy!r}")

    # Partial compliance: only a fraction of targeted agents actually comply
    if compliance_fraction < 1.0:
        n_comply = max(1, int(compliance_fraction * len(idx)))
        idx = rng.choice(idx, size=n_comply, replace=False)

    agents.inoculated[idx] = True
    agents.susceptibility[idx] *= kappa


# ── Seeding schedule ──────────────────────────────────────────────────────────

def get_seed_fraction_at_step(
    regime: str,
    step: int,
    n_steps: int,
    base_fraction: float,
    dose_matched: bool,
    total_fraction_override: Optional[float] = None,
) -> float:
    """Return the fraction of agents to seed externally at a given step.

    ``total_fraction_override`` supports dose-span experiments by specifying the
    ex-ante cumulative direct-seeding budget for the active regime.  The budget
    is distributed over the regime's original temporal schedule, so only dose
    changes while timing remains single-shot, five-step burst, or continuous.
    Existing configurations remain bit-for-bit compatible when the override is
    absent.
    """
    if total_fraction_override is not None:
        if total_fraction_override < 0:
            raise ValueError("total_fraction_override must be non-negative")
        if regime == "single_shot":
            return total_fraction_override if step == 0 else 0.0
        elif regime == "burst":
            return total_fraction_override / 5.0 if step < 5 else 0.0
        elif regime == "continuous":
            return total_fraction_override / n_steps
    elif dose_matched:
        # Equate total seeding to single_shot (base_fraction * N total events)
        if regime == "single_shot":
            return base_fraction if step == 0 else 0.0
        elif regime == "burst":
            # Spread base_fraction over 5 steps
            return base_fraction / 5.0 if step < 5 else 0.0
        elif regime == "continuous":
            # Spread base_fraction over all steps
            return base_fraction / n_steps
    else:
        if regime == "single_shot":
            return base_fraction if step == 0 else 0.0
        elif regime == "burst":
            return base_fraction if step < 5 else 0.0
        elif regime == "continuous":
            return base_fraction
    raise ValueError(f"Unknown seeding regime: {regime!r}")


# ── One-step persuasion update ────────────────────────────────────────────────

def persuasion_step(
    g: nx.Graph,
    agents: AgentState,
    delta_m: float,
    is_labeled: bool,
    step: int,
    cfg_sim: dict,
    seeding_rng: np.random.Generator,
    sharing_rng: np.random.Generator,
    noise_rng: np.random.Generator,
    seed_fraction_this_step: float,
    label_loss_sharing: bool = False,
    decay_rate: float = 0.0,
) -> dict[str, int]:
    """Apply one step of exogenous seeding + first-order neighbor sharing (in-place)."""
    n = len(agents.opinions)
    opinions = agents.opinions
    target = cfg_sim["target_position"]
    lam = cfg_sim["disclosure_lambda"]
    alpha = cfg_sim["second_hand_attenuation"]
    p_share = cfg_sim["sharing_probability"]
    noise_sd = delta_m * cfg_sim["noise_scale"]
    act_thresh = cfg_sim["activation_threshold"]

    # Effective susceptibility with optional decay
    susc = agents.susceptibility.copy()
    if decay_rate > 0:
        susc *= (1.0 - decay_rate) ** agents.cumulative_exposure

    # ── Stage 1: Exogenous seeding ────────────────────────────────────────────
    k = max(1, int(seed_fraction_this_step * n))
    seed_idx = seeding_rng.choice(n, size=k, replace=False)

    deltas = np.zeros(n)
    for idx in seed_idx:
        pull = target - opinions[idx]
        d = delta_m * susc[idx] * pull
        if is_labeled:
            d *= max(0.0, 1.0 - lam * agents.disclosure_sensitivity[idx])
        d += noise_rng.normal(0, noise_sd)
        deltas[idx] += d

    # Mark activated agents
    activated = np.where(np.abs(deltas) > act_thresh)[0]
    agents.cumulative_exposure[seed_idx] += 1
    agents.direct_exposure[seed_idx] += 1

    # ── Stage 2: First-order neighbor sharing ────────────────────────────────
    second_hand_deltas = np.zeros(n)
    secondhand_events = 0
    for node in activated:
        for nbr in g.neighbors(node):
            if sharing_rng.random() < p_share:
                pull_nbr = target - opinions[nbr]
                d_nbr = alpha * delta_m * susc[nbr] * pull_nbr
                if is_labeled and not label_loss_sharing:
                    d_nbr *= max(0.0, 1.0 - lam * agents.disclosure_sensitivity[nbr])
                d_nbr += noise_rng.normal(0, alpha * noise_sd)
                second_hand_deltas[nbr] += d_nbr
                agents.cumulative_exposure[nbr] += 1
                agents.secondhand_exposure[nbr] += 1
                secondhand_events += 1

    # ── Apply and clip ────────────────────────────────────────────────────────
    agents.opinions = np.clip(opinions + deltas + second_hand_deltas, -1.0, 1.0)
    return {"direct_exposures": int(k), "secondhand_exposures": int(secondhand_events)}


# ── Primary outcomes ──────────────────────────────────────────────────────────

def compute_outcomes(initial_opinions: np.ndarray, final_opinions: np.ndarray) -> dict:
    """Compute mean total shift (Eq. 4), mean signed shift (Eq. 5), and conversion rate (Eq. 6)."""
    delta = final_opinions - initial_opinions
    total_shift = float(np.mean(np.abs(delta)))                  # Eq. 4

    target = 0.6
    direction = np.sign(target - initial_opinions)
    signed_shift = float(np.mean(delta * direction))             # Eq. 5 (directional)

    opposed = initial_opinions < 0
    if opposed.sum() > 0:
        conversion_rate = float(np.mean(final_opinions[opposed] > 0))  # Eq. 6
    else:
        conversion_rate = 0.0

    return {
        "total_shift": total_shift,
        "signed_shift": signed_shift,
        "conversion_rate": conversion_rate,
    }


def compute_exposure_metrics(agents: AgentState) -> dict:
    """Return run-level assigned/realized exposure summaries."""
    total = agents.cumulative_exposure
    direct = agents.direct_exposure
    secondhand = agents.secondhand_exposure
    n = len(total)
    return {
        "mean_cumulative_exposure": float(np.mean(total)),
        "total_direct_exposures": int(np.sum(direct)),
        "total_secondhand_exposures": int(np.sum(secondhand)),
        "total_exposures": int(np.sum(total)),
        "unique_directly_exposed": int(np.count_nonzero(direct >= 1)),
        "unique_any_exposed": int(np.count_nonzero(total >= 1)),
        "fraction_any_exposed": float(np.count_nonzero(total >= 1) / n),
        "fraction_repeated_exposure": float(np.count_nonzero(total >= 2) / n),
        "sd_cumulative_exposure": float(np.std(total, ddof=0)),
        "median_cumulative_exposure": float(np.median(total)),
        "p90_cumulative_exposure": float(np.percentile(total, 90)),
        "max_cumulative_exposure": int(np.max(total)),
    }


def gini_nonnegative(values: np.ndarray) -> float:
    """Gini coefficient for a finite non-negative vector."""
    x = np.sort(np.asarray(values, dtype=float))
    if len(x) == 0 or x.sum() == 0:
        return 0.0
    index = np.arange(1, len(x) + 1, dtype=float)
    return float((2.0 * np.sum(index * x) / (len(x) * x.sum())) - (len(x) + 1) / len(x))


def compute_mechanism_metrics(
    initial_opinions: np.ndarray,
    agents: AgentState,
    outcomes: dict,
    direct_by_step: list[int],
    secondhand_by_step: list[int],
    shift_by_step: list[float],
    cumulative_shift_by_step: list[float],
) -> dict:
    """Compute dynamic, clipping, spillover, and exposure-stratified diagnostics."""
    final_opinions = agents.opinions
    total_by_step = [d + s for d, s in zip(direct_by_step, secondhand_by_step)]
    total_events = float(sum(total_by_step))
    exposure_hhi = (
        float(np.sum((np.asarray(total_by_step, dtype=float) / total_events) ** 2))
        if total_events > 0
        else 0.0
    )
    final_total_shift = outcomes["total_shift"]
    threshold = 0.8 * final_total_shift
    time_to_80 = next(
        (step + 1 for step, value in enumerate(cumulative_shift_by_step) if value >= threshold),
        len(cumulative_shift_by_step),
    )
    exposed = agents.cumulative_exposure >= 1
    unexposed = ~exposed
    absolute_shift = np.abs(final_opinions - initial_opinions)
    mean_shift_exposed = float(absolute_shift[exposed].mean()) if exposed.any() else float("nan")
    mean_shift_unexposed = float(absolute_shift[unexposed].mean()) if unexposed.any() else float("nan")
    mean_exposure = float(np.mean(agents.cumulative_exposure))
    return {
        "direct_exposures_by_step": json.dumps(direct_by_step, separators=(",", ":")),
        "secondhand_exposures_by_step": json.dumps(secondhand_by_step, separators=(",", ":")),
        "total_exposures_by_step": json.dumps(total_by_step, separators=(",", ":")),
        "opinion_shift_by_step": json.dumps(shift_by_step, separators=(",", ":")),
        "cumulative_total_shift_by_step": json.dumps(cumulative_shift_by_step, separators=(",", ":")),
        "peak_exposure_step": int(np.argmax(total_by_step) + 1),
        "peak_shift_step": int(np.argmax(shift_by_step) + 1),
        "time_to_80pct_final_shift": int(time_to_80),
        "exposure_temporal_concentration": exposure_hhi,
        "persuasion_efficiency": float(outcomes["signed_shift"] / mean_exposure),
        "exposure_spillover_reach": float(np.mean(agents.secondhand_exposure >= 1)),
        "final_opinion_mean": float(np.mean(final_opinions)),
        "final_opinion_sd": float(np.std(final_opinions, ddof=0)),
        "final_opinion_gini": gini_nonnegative(np.abs(final_opinions)),
        "boundary_clip_rate": float(np.mean((final_opinions <= -1.0 + 1e-12) | (final_opinions >= 1.0 - 1e-12))),
        "exposed_agent_count": int(np.count_nonzero(exposed)),
        "unexposed_agent_count": int(np.count_nonzero(unexposed)),
        "mean_shift_exposed_agents": mean_shift_exposed,
        "mean_shift_unexposed_agents": mean_shift_unexposed,
    }


# ── Single replication ────────────────────────────────────────────────────────

def run_single(
    topology: str,
    message_condition: str,
    delta_m: float,
    inoculation: str,
    seeding_regime: str,
    cfg_sim: dict,
    replication: int,
    robustness_overrides: Optional[dict] = None,
    seed_override: Optional[dict] = None,
    seed_namespace: str = "",
    paired_seed_namespace: str = "",
    run_metadata: Optional[dict] = None,
) -> dict:
    if seed_override is not None:
        # Replay exact seeds from either a legacy or strict manifest.
        master_seed = seed_override.get("master_seed")
        seed_net  = seed_override["seed_net"]
        seed_attr = seed_override["seed_attr"]
        seed_sim  = seed_override.get("seed_sim")
        seed_seeding = seed_override.get("seed_seeding", seed_sim)
        seed_sharing = seed_override.get("seed_sharing", seed_sim)
        seed_noise = seed_override.get("seed_noise", seed_sim)
        seed_inoc = seed_override["seed_inoc"]
    else:
        cell_key = f"{topology}|{message_condition}|{inoculation}|{seeding_regime}"
        if paired_seed_namespace:
            # The design/dose label is deliberately excluded, so corresponding
            # runs across dose spans share all baseline random streams.
            master_seed = stable_hash_int(
                f"{paired_seed_namespace}|{cell_key}|{replication}", modulo=2**63 - 1
            )
            seed_net = stable_hash_int(f"{master_seed}|network", modulo=2**63 - 1)
            seed_attr = stable_hash_int(f"{master_seed}|initialization", modulo=2**63 - 1)
            seed_seeding = stable_hash_int(f"{master_seed}|seeding", modulo=2**63 - 1)
            seed_sharing = stable_hash_int(f"{master_seed}|sharing", modulo=2**63 - 1)
            seed_noise = stable_hash_int(f"{master_seed}|noise", modulo=2**63 - 1)
            seed_inoc = stable_hash_int(f"{master_seed}|inoculation", modulo=2**63 - 1)
            seed_sim = None
        elif seed_namespace:
            # Extension designs use a full 31-bit hash that includes the
            # replication index.  This avoids the collision-prone legacy
            # ``hash % 10000 + replication * 97`` scheme while leaving legacy
            # fresh reruns and manifest replay unchanged.
            base_seed = stable_hash_int(
                f"{seed_namespace}|{cell_key}|{replication}", modulo=2**31 - 5
            )
            master_seed = None
        else:
            base_seed = replication * 97 + stable_hash_int(cell_key)
            master_seed = None
        if not paired_seed_namespace:
            seed_net  = (base_seed + 1) % (2**31)
            seed_attr = (base_seed + 2) % (2**31)
            seed_sim  = (base_seed + 3) % (2**31)
            seed_seeding = seed_sim
            seed_sharing = seed_sim
            seed_noise = seed_sim
            seed_inoc = (base_seed + 4) % (2**31)

    cfg = dict(cfg_sim)
    if robustness_overrides:
        cfg.update(robustness_overrides)

    label_loss = cfg.pop("label_loss_sharing", False)
    decay_rate = cfg.pop("decay_rate", 0.0)
    opinion_reversion_mu = float(cfg.pop("opinion_reversion_mu", 0.0))
    if not 0.0 <= opinion_reversion_mu < 1.0:
        raise ValueError("opinion_reversion_mu must lie in [0, 1)")
    compliance = cfg.pop("compliance_fraction", 1.0)

    agents = init_agents(cfg["n_agents"], seed_attr)
    initial_opinions = agents.opinions.copy()

    g = build_network(topology, cfg["n_agents"], agents.opinions, seed_net)
    apply_inoculation(
        g, agents, inoculation,
        cfg["inoculation_budget_fraction"],
        cfg["inoculation_kappa"],
        compliance,
        seed_inoc,
    )

    is_labeled = (message_condition == "labeled_ai")
    seeding_rng = np.random.default_rng(seed_seeding)
    sharing_rng = np.random.default_rng(seed_sharing)
    noise_rng = np.random.default_rng(seed_noise)
    dose_matched = cfg.get("dose_matched", False)
    dose_totals = cfg.get("seeding_total_fractions")
    total_fraction_override = None
    if dose_totals is not None:
        if seeding_regime not in dose_totals:
            raise KeyError(
                f"seeding_total_fractions missing regime: {seeding_regime!r}"
            )
        total_fraction_override = float(dose_totals[seeding_regime])

    active_steps = 0
    assigned_direct_seed_events = 0
    seeded_per_active_step = None
    direct_by_step = [0] * cfg["n_steps"]
    secondhand_by_step = [0] * cfg["n_steps"]
    shift_by_step = [0.0] * cfg["n_steps"]
    cumulative_shift_by_step = [0.0] * cfg["n_steps"]
    for step in range(cfg["n_steps"]):
        frac = get_seed_fraction_at_step(
            seeding_regime, step, cfg["n_steps"],
            cfg["seed_fraction"], dose_matched, total_fraction_override,
        )
        opinions_before_step = agents.opinions.copy()
        if frac > 0:
            k = max(1, int(frac * cfg["n_agents"]))
            active_steps += 1
            assigned_direct_seed_events += k
            if seeded_per_active_step is None:
                seeded_per_active_step = k
            elif seeded_per_active_step != k:
                raise ValueError("Strict archive requires a constant per-active-step seed count")
            step_exposures = persuasion_step(
                g, agents, delta_m, is_labeled, step, cfg,
                seeding_rng, sharing_rng, noise_rng, frac,
                label_loss_sharing=label_loss,
                decay_rate=decay_rate,
            )
            direct_by_step[step] = step_exposures["direct_exposures"]
            secondhand_by_step[step] = step_exposures["secondhand_exposures"]
        # Positive-control boundary variant: reversion operates after every
        # time step, including steps without direct seeding. At mu=0 this is
        # an exact no-op and preserves the frozen benchmark equations.
        if opinion_reversion_mu > 0.0:
            agents.opinions = np.clip(
                (1.0 - opinion_reversion_mu) * agents.opinions
                + opinion_reversion_mu * initial_opinions,
                -1.0,
                1.0,
            )
        shift_by_step[step] = float(np.mean(np.abs(agents.opinions - opinions_before_step)))
        cumulative_shift_by_step[step] = float(
            np.mean(np.abs(agents.opinions - initial_opinions))
        )

    outcomes = compute_outcomes(initial_opinions, agents.opinions)
    exposures = compute_exposure_metrics(agents)
    mechanism_metrics = compute_mechanism_metrics(
        initial_opinions,
        agents,
        outcomes,
        direct_by_step,
        secondhand_by_step,
        shift_by_step,
        cumulative_shift_by_step,
    )
    metadata = dict(run_metadata or {})
    result = {
        **metadata,
        "topology": topology,
        "message_condition": message_condition,
        "message_strength": delta_m,
        "delta_m": delta_m,
        "inoculation_strategy": inoculation,
        "inoculation": inoculation,
        "inoculation_budget": 0.0 if inoculation == "none" else cfg["inoculation_budget_fraction"],
        "seeding_regime": seeding_regime,
        "active_steps": active_steps,
        "seeded_per_active_step": seeded_per_active_step,
        "assigned_direct_seed_events": assigned_direct_seed_events,
        "opinion_reversion_mu": opinion_reversion_mu,
        "replicate_id": replication + 1,
        "replication": replication,
        "N_agents": cfg["n_agents"],
        "T_steps": cfg["n_steps"],
        "master_seed": master_seed,
        "network_seed": seed_net,
        "initialization_seed": seed_attr,
        "seeding_seed": seed_seeding,
        "sharing_seed": seed_sharing,
        "noise_seed": seed_noise,
        "inoculation_seed": seed_inoc,
        "seed_net": seed_net,
        "seed_attr": seed_attr,
        "seed_sim": seed_sim,
        "seed_seeding": seed_seeding,
        "seed_sharing": seed_sharing,
        "seed_noise": seed_noise,
        "seed_inoc": seed_inoc,
        **exposures,
        **mechanism_metrics,
        "mean_total_shift": outcomes["total_shift"],
        "mean_signed_shift": outcomes["signed_shift"],
        **outcomes,
    }
    return result


# ── Main runner ───────────────────────────────────────────────────────────────

def main():
    args = parse_args()
    cfg = load_config(args.config)
    manifest = load_seed_manifest(args.seed_manifest) if args.seed_manifest else None
    if manifest is not None:
        print(f"Replaying seeds from manifest: {args.seed_manifest} ({len(manifest)} cells)")

    design = cfg["design"]
    cfg_sim = cfg["simulation"]
    out_dir = Path(cfg["output"]["dir"])
    out_dir.mkdir(parents=True, exist_ok=True)

    topologies = design["topologies"]
    conditions = design["message_conditions"]   # {name: delta_m}
    inoculations = design["inoculation_strategies"]
    regimes = design["seeding_regimes"]
    n_reps = design["replications"]
    replication_start = int(design.get("replication_start", 0))
    if replication_start < 0:
        raise ValueError("replication_start must be nonnegative")
    seed_namespace = design.get("seed_namespace", "")
    paired_seed_namespace = design.get("paired_seed_namespace", "")
    config_path = Path(args.config)
    model_path = Path(__file__)
    model_hash = hashlib.sha256(model_path.read_bytes()).hexdigest()
    config_hash = hashlib.sha256(config_path.read_bytes()).hexdigest()
    run_metadata_base = {
        "design_id": design["name"],
        "design_class": design.get("design_class", "unspecified"),
        "design_family": design.get("design_family", design.get("design_class", "unspecified")),
        "dose_span_ratio": design.get("dose_span_ratio"),
        "dose_center": design.get("dose_center"),
        "dose_spread": design.get("dose_spread"),
        "dose_anchor": design.get("dose_anchor"),
        "strength_anchor": design.get("strength_anchor"),
        "structural_variant": design.get("structural_variant", "baseline"),
        "message_strength_scheme": design.get("message_strength_scheme", "unspecified"),
        "config_id": config_path.name,
        "config_sha256": config_hash,
        "model_version": f"sha256:{model_hash}",
        "output_version": cfg.get("output", {}).get("version", "legacy-unversioned"),
    }

    total = len(topologies) * len(conditions) * len(inoculations) * len(regimes) * n_reps
    print(f"\nDesign: {design['name']}")
    print(f"  {len(topologies)} topologies × {len(conditions)} conditions × "
          f"{len(inoculations)} inoculations × {len(regimes)} regimes × {n_reps} reps "
          f"(indices {replication_start}–{replication_start + n_reps - 1}) "
          f"= {total} runs")

    rows = []
    seeds_rows = []
    t0 = time.time()
    count = 0

    for topo in topologies:
        for cond, delta_m in conditions.items():
            for inocu in inoculations:
                for regime in regimes:
                    for rep in range(replication_start, replication_start + n_reps):
                        if manifest is not None:
                            key = (topo, cond, inocu, regime, rep)
                            if key not in manifest:
                                raise KeyError(
                                    f"Seed manifest missing cell: {key}. "
                                    f"Exact replay requires a complete manifest."
                                )
                            seed_override = manifest[key]
                        else:
                            seed_override = None
                        row = run_single(
                            topology=topo,
                            message_condition=cond,
                            delta_m=delta_m,
                            inoculation=inocu,
                            seeding_regime=regime,
                            cfg_sim=dict(cfg_sim),
                            replication=rep,
                            seed_override=seed_override,
                            seed_namespace=seed_namespace,
                            paired_seed_namespace=paired_seed_namespace,
                            run_metadata={
                                **run_metadata_base,
                                "run_timestamp": datetime.now(timezone.utc).isoformat(),
                            },
                        )
                        rows.append(row)
                        seeds_rows.append({
                            "topology": topo, "message_condition": cond,
                            "inoculation": inocu, "seeding_regime": regime,
                            "replication": rep,
                            "master_seed": row["master_seed"],
                            "network_seed": row["network_seed"],
                            "initialization_seed": row["initialization_seed"],
                            "seeding_seed": row["seeding_seed"],
                            "sharing_seed": row["sharing_seed"],
                            "noise_seed": row["noise_seed"],
                            "inoculation_seed": row["inoculation_seed"],
                            "seed_net": row["seed_net"],
                            "seed_attr": row["seed_attr"],
                            "seed_sim": row["seed_sim"],
                            "seed_seeding": row["seed_seeding"],
                            "seed_sharing": row["seed_sharing"],
                            "seed_noise": row["seed_noise"],
                            "seed_inoc": row["seed_inoc"],
                        })
                        count += 1
                        if count % 100 == 0:
                            elapsed = time.time() - t0
                            eta = elapsed / count * (total - count)
                            print(f"  [{count}/{total}] ETA {eta:.0f}s")

    # Save raw results
    out_csv = out_dir / "raw_results.csv"
    if rows:
        fieldnames = list(rows[0].keys())
        with open(out_csv, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(rows)
    print(f"\nSaved {len(rows)} rows → {out_csv}")

    # Save seed manifest
    manifest_path = out_dir / cfg["output"]["seed_manifest"]
    if seeds_rows:
        with open(manifest_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=list(seeds_rows[0].keys()))
            writer.writeheader()
            writer.writerows(seeds_rows)
    print(f"Saved seed manifest → {manifest_path}")
    print(f"Total time: {time.time()-t0:.1f}s")


if __name__ == "__main__":
    main()
